### PR TITLE
Allow Symfony 5 components

### LINKED ISSUE #100: User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated
User Deprecated: Passing a command as string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor if you need features provided by the shell

### PR DESCRIPTION
**Pull request by Lustmored**
Also closes #100 - use new Process method to create object from shell command when available

### CODE REVIEW

**Comment by COil** [comment]
Hi @Lustmored , thanks for the PR.
The travis build fails:

Problem 1

    - symfony/console v5.0.0 requires php ^7.2.5 -> your PHP version (7.1.27) does not satisfy that requirement.

As 7.1 is EOL, I think we should change the version to 7.2.  Can you make a try please?

**Comment by gustawdaniel** [comment]
Can I please accept this pull request?

**Comment by COil** [comment]
The PR can't be accepted as checks are failing. The PHP version requirements must be changed to ^7.2.5

**Comment by Lustmored** [comment]
Sorry guys for taking long to answer, didn't receive notifications somehow. I am experimenting with PHP version constraints, not a Travis master but will do my best.

**Comment by Lustmored** [comment]
I've allowed myself to bump PHP dependency in composer.json and extended test config with 3 major Symfony versions (3.4, 4.4 and 5.0). I am not sure it actually tests against components from specified version. but couldn't find better solution.

Anyways all tests are passing right now. Once again sorry for the delay.

**Comment by COil** [comment]
Hi @javiereguiluz Any chance to have this merged and a new tag?

**Comment by daum** [comment]
@javiereguiluz  Do you have a timeline for the merge on this?

**Comment by javiereguiluz** [comment]
I'm sorry it took me so long to merge this ... thank you all who contributed to this fix.

**Comment by COil** [comment]
Thanks Javier, I will check this on a newly created Symfony5 project tonight. See you. :)

**Pull request merged**
